let myjokes = [
  {
    category: "Pun",
    type: "single",
    joke: 'Two fish in a tank. One turns to the other and says, "Do you know how to drive this thing?"',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 185,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "The glass is neither half-full nor half-empty, the glass is twice as big as it needs to be.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 23,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Your momma is so fat, you need to switch to NTFS to store a picture of her.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    id: 55,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Your mama's so FAT she can't save files bigger than 4GB.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    id: 9,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'A SQL statement walks into a bar and sees two tables.\nIt approaches, and asks "may I join you?"',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 5,
    safe: true,
    lang: "en",
  },
  {
    category: "Dark",
    type: "single",
    joke: "I was going to tell a dead baby joke. But I decided to abort.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    id: 207,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "A programmer puts two glasses on his bedside table before going to sleep.\nA full one, in case he gets thirsty, and an empty one, in case he doesn't.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 3,
    safe: true,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: "I was struggling to figure out how lightning works, but then it struck me.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 220,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: '"We messed up the keming again guys."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 20,
    safe: true,
    lang: "en",
  },
  {
    category: "Dark",
    type: "single",
    joke: "I don't know where I stand on abortion. I like killing babies, but I don't like giving women a choice.",
    flags: {
      nsfw: true,
      religious: false,
      political: false,
      racist: false,
      sexist: true,
      explicit: true,
    },
    id: 228,
    safe: false,
    lang: "en",
  },
];

let index = Math.floor(Math.random() * myjokes.length - 1);
console.log(index);
id1.innerHTML = myjokes[index].joke;
